### ISSUE TITLE
VST/VSTi wrappers

### ISSUE THREAD

**Issue by x42** [pantherb/setBfree#12]
expose effects as  x-platform VST, synth as VSTi.

probably only after GUI #3 rewrite --  strictly speaking a GUI is not really necessary, but VST users are spoiled by look&feel :)

**Comment by x42** [comment]
Aah well. VST is 90's technology best deprecated rather sooner than later :)

Go LV2 Go!

**Comment by bryc** [comment]
> Aah well. VST is 90's technology best deprecated rather sooner than later :)

More likely that LV2 will fizzle out before it even gains traction. 5 years later and nothing supports LV2. Not even LMMS, which is Linux as well. Both Ardour Linux users, I'm guessing?
