### ISSUE TITLE
ALSA tab

### ISSUE THREAD

**Issue by shdawson** [pantherb/setBfree#28]
Hi,

I have a new MIDI controller, a KORG nanoKEY2. The controller works fine with ZynAddSubFX. The controller does not show up in the QjackCtl ALSA tab with setBfree.

I dragged the setBfree icon to my text editor. I see the following
information:

[Desktop Entry]
Type=Application
Name=setBfree
GenericName=DSP tonewheel organ
Comment=MIDI-controlled, software synthesizer using JACK
Icon=setBfree
Exec=setBfree-start
Terminal=false
Categories=AudioVideo;Audio;

I am guessing the setBfree icon I am clicking on is not firing up setBfree with the necessary parameters, to see the nanoKEY2 on the ALSA tab in QjackCtl. Is this hypothesis correct? If so, can you please provide the syntax I need to run from the command line, so setBfree can see the nanoKEY2, so I can use the nanoKEY2 to play setBfree? setBfree --help  from the command line certainly provides loads of information, but it is not clear to me what syntax I need to run.

Thank You,
SHD

**Comment by x42** [comment]
For future reference: The new GUI is either LV2-plugin or jack-only.

As for setting up jack (and jack midi) please see the excellent tutorial at:
http://libremusicproduction.com/articles/demystifying-jack-%E2%80%93-beginners-guide-getting-started-jack  or  http://manual.ardour.org/setting-up-your-system/setting-up-midi/midi-on-linux/

alsa-midi support is still available in the headless commandline app (and will not go away), but migrating to jack-midi is highly recommended.
