### ISSUE TITLE
New install.  Crashes my Ubuntu 14.04

### ISSUE THREAD

**Issue by bluuplanet** [pantherb/setBfree#29]
I just installed this program.  Computer is an Acer AM1610-U1201A.
I have an M-Audio Keystation 61es connected by USB
When I start up setBfree, I see the drawbars and buttons and keyboards.  I can adjust drawbars and press buttons at first.
The M-audio keyboard is apparently not recognized.
When I click any of the keys in the setBfree window, my computer locks up.  I can't close the program. program buttons stop working. 
I have to hold my power button in for 10 seconds to turn off my computer.

**Comment by x42** [comment]
no feeback in 3 months, closing this issue. Many other users report it working just fine on ubuntu.
