### ISSUE TITLE
setBfree installation+sound problem!

### ISSUE THREAD

**Issue by zenoxv** [pantherb/setBfree#30]
Hi, when i'm trying to install setBfree as it should be installed on linux(raspbian) (cd /home/pi/src/setBfree-master -> make ) i get an error : 

-c -o overdrive.o overdrive.c
ccl;error:unrecognized command line option '-msse'
ccl;error:unrecognized command line option '-msse2'
ccl;error:unrecognized command line option '-mfpmath=sse'
Makefile:45: recipe for target 'overdrive.o' failed
make[1]: *** [overdrive.o] Error 1
make[1]: Leaving directory '/home/pi/src/setBfree-master/b_overdrive'
Makefile:17:recipe for target 'b_overdrive' failed
make: *** [b_overdrive] Error 2

Meanwhile, if i delete those 3 commands (-msse,-msse2,-mfpmath=sse) from common.mak i get it installed and it works pretty good ,till im trying to play on my midi keyboard(plugged,configured with jack and dozens of diffrents ways were tried) when i'm pressing too much notes at the same time (specially black and white(from Fa to Si or more) i get a noise and it stucks for few seconds(for some settings in Jack it even stops de system from responding) so i thought that maybe those 3 commands that i have removed in the installation are the reason for that, becose i've tried lots of different settings and even bought an additional usb sound card in case that the RPI was too weak ,but all the same...

What does helped a little with de sound, was enabling the realtime mode in jack and setting the Dither to triangular ,but the noise continues, a little weaker, but it still too loud and stuck for about a second(impossible to play ).

Every additional program that you proposed i have installed and the Jack Audio works without any error messages so i have really no idea what is the reason for such a problem(i'm new to Linux ). 

Any suggestions will be appreciated !

**Comment by x42** [comment]
I had/have it working on a very similar ARM device (MK802). I don't own a RPi myself but know it can work there, too.
