### ISSUE TITLE
Font path for Fedora

### ISSUE THREAD

**Issue by Baggypants** [pantherb/setBfree#31]
When I try to build the gui it fails with 
Makefile:17: "GUI will not be built"
Makefile:18: "either openGL/GLU is not available - install glu-dev, ftgl-dev"
Makefile:19: "or /usr/share/fonts/truetype/ttf-bitstream-vera/VeraBd.ttf cannot be found"

In Fedora (21) it is /usr/share/fonts/bitstream-vera/VeraBd.ttf provided by the bitstream-vera-sans-fonts package

**Comment by x42** [comment]
The font can be specified at compile time. In your case:

`make FONTFILE= /usr/share/fonts/bitstream-vera/VeraBd.ttf`
