### ISSUE TITLE
laptop keyboard drawbar control

### ISSUE THREAD

**Issue by Baggypants** [pantherb/setBfree#32]
I've not managed to compile the gui for reasons. I'd like to gig this on a laptop and not have to shell out for MIDI control surfaces but as far as I can see the GUI requires mouse control to move the drawbars (I might be wrong).
wouldn't it be easier if laptop keys were mapped to the upper manual drawbars

```
1 2 3 4 5 6 7 8 9    <--- Drawbar-number
Q W E R T Y U I O    <--- fader pipe down (push drawbar in)
A S D F G H J K L    <--- fade pipe up (pull drawbar out)
```

and maybe keys z x c v being mapped to Reverb, Brightness, perc 4' perc 2 2/3 and other things like presets or something (number keys?).

Or is there another jack/alsamidi program I could use to do this?

**Comment by x42** [comment]
Why not just map midi-CCs from the keyboard?

Pressing [laptop] keyboard keys + [piano] keyboard keys at the same time strikes me as unsuitable for a live gig.

The main reason why this is not implemented is: The application needs focus to receive keyboard events. If you accidentally move the mouse (or Alt+tab, etc) the key-presses go somewhere else.  Synchronization is another issue: Keyboard I/O has an undefined latency.

I would guess that some apps can do this regardless - midish.org maybe.  Whipping up a pure-data or supercollider patch to generate midi from keyboard entry is also trivial (if I remember correctly it's one of the examples/tutorials). But for above stated reason, I don't think you'll find any professional-tool for computer-keyboard to MIDI.

**Comment by x42** [comment]
aah well. I'll eat my words :)

I've just prototyped this. press <tab> to toggle keyboard grab. then `Q-P,A-L` modify the drawbars.  1,2,3 selects which manual is affected.

I'll have to experiment regarding the keybindings. maybe add some more...

**Comment by shdawson** [comment]
Nice!

There is more capability here than meets the eye. I suspect  you will be happy with where this functionality goes. It could be a missing link to growing the software project. Without real time control, it is difficult to use the app.

-S

**Comment by x42** [comment]
We'll see. 

In an ideal world those shortcuts are not needed. But for those of us who don't live in an ideal world, I see that they are a viable alternative interface.

There are various 'virtual keyboard apps'  e.g. vkeybd. vmpk, etc.. yet most of them focus on note-level, not the control. So it does indeed make some sense to offer the latter in setBfree's UI.

Currently US-keyboard layout is hardcoded, but that's something to sort out in the future. Maybe offer dynamic or user-specific key-shortcut assignments.

Experimenting a bit, I find using 1-9 to recall presets (MIDI program load) handy. Other controls should be mapped as well... give me a couple of minutes :)

**Comment by Baggypants** [comment]
This works exactly how I wanted, the ability to configure keys would be helpful as I'm on a UK keyboard. It's not too bad but \ isn't with [ and ]
