### ISSUE TITLE
Cannot build on MIPS

### ISSUE THREAD

**Issue by rekado** [pantherb/setBfree#35]
setbfree 0.8.0 cannot be built on MIPS because the build system sets a couple of flags that are not supported on MIPS, such as `-msse`.  Full build output can be found here:

http://hydra.gnu.org/build/561204/nixlog/1/raw

**Comment by x42** [comment]
Please see https://github.com/pantherb/setBfree/#compile there's a note to packagers.

tl;dr run  `make OPTIMIZATIONS="-O2"`  or similar appropriate to the architecture.
The default optimizations are intended for x86. For ARM, armhf, mips etc different optimizations apply.

**Comment by x42** [comment]
PS. default optimizations are in `common.mak` (as make variable that can be overridden)

```
OPTIMIZATIONS ?= -msse -msse2 -mfpmath=sse -ffast-math -fomit-frame-pointer -O3 -fno-finite-math-only
```

**Comment by rekado** [comment]
Ah, thanks.  I shall try that.
