### ISSUE TITLE
Is jboverdrive expected to be installed?

### ISSUE THREAD

**Issue by trebmuh** [pantherb/setBfree#46]
Hi,
I'm using setbfree from the debian stretch repo. I saw that there is a `jboverdrive` manpage installed by the package which (when reading at) looks to be a binary that I could use from the command line. That said, the debian package doesn't provide such a binary.
Before getting in touch with the debian people, I'd like to ask here if this `jboverdrive` binary is expected to be installed from your upstream point of view?
Thanks.

**Comment by x42** [comment]
Sorry for the late reply. I somehow missed the notification about this.

The answer is no. Even deploying the `b_overdrive.lv2` plugin is questionable. It's mostly just an experiment and does not sound very good. -- see also #17

**Comment by trebmuh** [comment]
OK. Thanks.
