### ISSUE TITLE
ARM - Crash - computeOffsets: Assertion `maxhn + w->hornSpacing[i] < ((unsigned int) (1 << 10))' failed.

### ISSUE THREAD

**Issue by brunetton** [pantherb/setBfree#47]
Hi, 
First of all, I want to thank you VERY much for this wonderful software. 
I'm currently trying to embed setBfree to a Raspberry-PI and use it as an Hammond emulator on stage.
As Raspbian version of setBfree is quite old (0.7.5), and new versions seems to "sounds better" (I am wrong ?) I wanted to compile a new version on the Pi(3).

Steps to reproduce: 
```
aptitude install libasound2-dev lv2-dev libglu1-mesa-dev ttf-bitstream-vera libjack-jackd2-dev libftgl-dev
git clone git@github.com:pantherb/setBfree.git
cd setBfree
make OPTIMIZATIONS=-O2
./src/setBfree
```
The result is :

```
init.. Audio : Oscillators : Scanner : Overdrive : Reverb : Whirl : setBfree: ../b_whirl/whirl.c:539: 
computeOffsets: Assertion `maxhn + w->hornSpacing[i] < ((unsigned int) (1 << 10))' failed.
Aborted
```

Did I missed something ? The problem seems to be in the Leslie simulation module. It's annoying, this is quite important for the sound !

Do you have any ideas ? Thanks !

**Comment by x42** [comment]
It's been a while since I've tried the jack-app on ARM. It may well be that special casing done for the LV2 plugin triggers this assertion. Sorry.

It's probably just some default values. I'll investigate, but I won't get my hands on a Rpi until next week. Please stay tuned.

**Comment by x42** [comment]
What samplerate are you using? Does it also cause this assertion when you use 48000 or 44100?

**Comment by brunetton** [comment]
Hi, thanks for your time ! 
And sorry for the delay, I didn't had time to work on that project for a while.
I'm using a 192kHz / 1024 frames/period Jack server ([IQaudio Pi-DAC-PRO](http://iqaudio.co.uk/hats/47-pi-dac-pro.html) card).

And ... it works well at 48kHz, you were right.
But letency is a big deal in that project that aims to be used on stage in live concert conditions.
Do you think I should open a feature request on the plugin repo ?

Thanks very much !

**Comment by x42** [comment]
Don't try to optimize (lower) latency by increasing the sample-rate. Especially with cheap cards such as the Pi-DAC, you'll usually get much worse quality compared to using 48k, besides chances are that your analog equipment cannot handle rates frequencies > 20kHz anyway and just distort instead.
Lower the buffersize if you must.
