### ISSUE TITLE
DIfference between programs number in pgm file and programs loaded by Program Change MIDI event

### ISSUE THREAD

**Issue by brunetton** [pantherb/setBfree#50]
Hi,

Steps to reproduce:

- define this program file:

    ```
    1 {
       name="All off",
       drawbars="000 0000 000",
      }

    2 {
       name="All on",
       drawbars="888 8888 888",
      }
    ```

- lunch `setbfree` with this program file
- connect [new](9309bd4f9df02e99f7dee5841afc0b13c33d36ec) setBfree output MIDI channel to any MIDI logger
- send to setBfree MIDI in: `Program Change 1`
- -> it loads the "All on" program, not "All off" program

Version: setBfree 9309bd4f9df02e99f7dee5841afc0b13c33d36ec (command line version)

**Comment by x42** [comment]
By default the CCs values for drawbars are inverted to work with motorized faders.

So drawbar "0" = Drawbar all the way to the top =  Fader all the way to the top = CC value 127.
while Drawbar "8" = Drawbar pulled out all the way = Fader at the bottom = CC value 0.

Try with a slight modification, that makes things more obvious:
```
1 {
  name="Almost All off",
  drawbars="000 0008 000",
  }

2 {
  name="Almost All on",
  drawbars="787 8888 888",
  }
```

And while you can configure this (suffix a minus (`-`) in the controller map, it seems to be a bug when sending feedback. I'll look into it.

**Comment by brunetton** [comment]
PS: I always close the issues I open ;) But I take some time to test before closing !

**Comment by x42** [comment]
Is it the off-by-one that is confusing you?

There is no "Program/Patch Change 0"  MIDI program/patches are numbered 1..128 (encoded as 0x00..0x7f)  - Same for MIDI-channels: Channel 1..16 are encoded as 0..15  (There's no channel zero, although this can be vendor specific).

**Comment by brunetton** [comment]
Answering to myself:

I just seen the **default** offset in config file ! Didn't seen it before !

```
## MIDI controller program number offset
## The value of this parameter should be equal to the number of the
## lowest program number on your MIDI controller. Some use 0 others 1.
##
#pgm.controller.offset=1
```

Setting it to 0 solve my offset problem :+1: 

=> maybe this should be 0 by default ? I was surprised seeing this activated by default.

Thanks again, and sorry for the time you spent reading this !

**Comment by x42** [comment]
I forgot that that was there. and yes it's to follow some vendor-preferences. It's been a while since I've seen a device that starts counting at zero.

**Comment by brunetton** [comment]
> Is it the off-by-one that is confusing you?

It was, yes

> PS. so yes to load program "N" (1 <= N <= 128) You send a message 0xc0(N-1) on the wire.

Exactly. And I thought program number was [0-127] coded, not the "human friendly" value.
Minor little thing that finally confused me.

Thanks again ... (I'll definitely have to pay you tons of beers !) :beers:

**Comment by brunetton** [comment]
> I forgot that that was there. and yes it's to follow some vendor-preferences. It's been a while since I've seen a device that starts counting at zero.

Probably I have no chance on this point: my [MK-361](https://medias.audiofanzine.com/images/normal/evolution-mk-361-2013625.jpg) starts counting from 0, and [jack-keyboard](http://jack-keyboard.sourceforge.net/) (that I use for testing) too :s

**Comment by x42** [comment]
NIce, I have not seen a device that starts counting at zero in a long time.
The 361 even has "000 Grand Piano" printed on it -- and I guess the 7seg LEDs also shows "000".

Anyway, there was indeed a bug about inverted CCs values (fixed now), so that's progress either way.
