### ISSUE TITLE
Vibrato switches MIDI CC values are linked

### ISSUE THREAD

**Issue by brunetton** [pantherb/setBfree#51]
Hi again. 
Still trying to get a full MIDI feedback with command line version, I came across some little things that you maybe would to be aware of. Here is one of those things:

Contrary to all percussion switches that all send 0 or 127 values, the two vibrato buttons sent values are "linked": the value sent by one depends of the actual value of the other:

| Vibrato lower | Vibrato upper | CC value |
|---------------|---------------|----------|
| off           | on -> off     | 0        |
| off           | off -> on     | 64       |
| on            | on -> off     | 32       |
| on            | off -> on     | 96       |
| on -> off     | off           | 0        |
| off -> on     | off           | 32       |
| on -> off     | on            | 64       |
| off -> on     | on            | 96       |

Is there any reason for that ?

Expected values:

| Vibrato lower | Vibrato upper | CC value |
|---------------|---------------|----------|
| off           | on -> off     | 0        |
| off           | off -> on     | 127      |
| on            | on -> off     | 0        |
| on            | off -> on     | 127      |
| on -> off     | off           | 0        |
| off -> on     | off           | 127      |
| on -> off     | on            | 0        |
| off -> on     | on            | 127      |

Thanks

**Comment by x42** [comment]
I'll have a look later, but some of those are intentional. You can use a knob rather than on/off switch to control both at the same time.

Leslie is another one that has a tristate and another combined control with 2^3 values (horn/woofer ^ chorale/off/tremolo)..

What MIDI-CC config are you using?

**Comment by brunetton** [comment]
Thanks (again) for your answer !

> some of those are intentional. You can use a knob rather than on/off switch to control both at the same time.

Ok, I get the point. But is this very coherent with percussion switches ?
Personally I'm very happy with percussion switches as I can represent them by 4 buttons in my Open Scene Control instance.

> Leslie is another one that has a tristate and another combined control with 2^3 values (horn/woofer ^ chorale/off/tremolo)..

I didn't noticed it but ... but I couldn't have noticed it anyway because [I don't get any Leslie feedback](https://github.com/pantherb/setBfree/issues/52#issuecomment-376289534) ;)
A priori, the choice of "multiplexing" values in one message makes things difficult for "decoding" those states back to 2 values for 2 different widget on controller side ! (But in my case, I planned to program custom widgets so I can manage, but this could be a problem for other people).

For a visual idea, here is my current O-S-C configuration for Leslie widget: a 3 state button
![Osc config screenshot](https://user-images.githubusercontent.com/86322/37935027-811e9e60-3150-11e8-9b48-6fe7665d6015.png)
(for now I'm only using upper keyboard)

Thanks !

**Comment by x42** [comment]
This should be fixed now -- along with #52. Please test.

**Comment by brunetton** [comment]
This issue can be closed as I answered on #51
