### ISSUE TITLE
Chorus/vibrato LV2 plugin doesn't launch

### ISSUE THREAD

**Issue by trebmuh** [pantherb/setBfree#62]
_Disclaimer: reading at [this](https://github.com/pantherb/setBfree/commit/ff2ea498f74671ce1051cec1738d9f3c71da8bec), I do understand that this might not be a priority for this project._

Building setBfree on a Stretch with `INSTALL_EXTRA_LV2=yes`, the chorus/vibrato LV2 plugin doesn't launch. Starting it in a CLI gives me:
```
$ jalv.gtk http://gareus.org/oss/lv2/b_chorato
Plugin:       http://gareus.org/oss/lv2/b_chorato
UI:           None
JACK Name:    setBfree Chorus/Vibrato
Sample rate:  48000 Hz
Block length: 256 frames
MIDI buffers: 32768 bytes
Comm buffers: 524288 bytes
Update rate:  25,0 Hz
lilv_lib_open(): error: Failed to open library /usr/lib/lv2/b_chorato/b_chorato.so (/usr/lib/lv2/b_chorato/b_chorato.so: undefined symbol: _Z17getVibratoRoutingP9b_tonegen)
Failed to instantiate plugin.
```

**Comment by x42** [comment]
Since it's a missing C++ symbol you also seem to have added `ENABLE_CONVOLUTION=yes` which forces the compiler to g++. I highly recommend to disable it (default is off).

If you have not set this option, please include a complete compile-log.

PS. The intention to split off the vibrato/chorus was mainly for the purpose of development, to allow to investigate issues without the synth itself.

**Comment by trebmuh** [comment]
> Since it's a missing C++ symbol you also seem to have added `ENABLE_CONVOLUTION=yes` which forces the compiler to g++. I highly recommend to disable it (default is off).

Thanks for the info @x42 . This flag is used here, and it comes from [the debian packaging](https://salsa.debian.org/multimedia-team/setbfree/blob/master/debian/rules#L12).

Would you recommend Debian not to use it as well?

**Comment by x42** [comment]
Yes, the cabinet emulation was never correct and should not be used.

I guess I should probably remove it, so that it is not inadvertently enabled by packagers.

**Comment by trebmuh** [comment]
I've committed the change [in the debian repo](https://salsa.debian.org/multimedia-team/setbfree/commit/c9548a081e9547a977bc8ddf99b00ae78f0c5f3d).

**Comment by x42** [comment]
Merci beaucoup.

**Comment by x42** [comment]
I've just tagged v0.8.8, that may help to push a new version with the changes.
