### ISSUE TITLE
Whirl GUI on Linux with Ardour & cross compiling issue

### ISSUE THREAD

**Issue by GeorgeNs** [pantherb/setBfree#64]
Thanks for all this amazing stuff.

1.I have tried to compile the setBfree and i could use it with success on linux as standalone and plugin too.
However, trying to compile and use individual parts of this project,such as whirl,I could still use the plugin but the GUI .so file it seems doesn't work,thus i can only open the gui provided by ardour. I didn't get any errors during building time, is this normal or i miss something?The whirl standalone works without issues.

2.Also i tried to cross compile it for windows but compilation stuck on gobject_init_ctor() constructor issue that says it is not declared in this scope...glib and necessary libraries are installed.
Is there any workaround or is the cross compiling kind impossible?

Cheers

**Comment by GeorgeNs** [comment]
1.Thank you,now individual parts can be compiled and open their gui in ardour too

2.I will try this one day,currently i have the mxe environment with the shared mingw32 version(x86_64) and it has its packages ready,so i need to change many things there,remove and recompile.
Probably I will need the static version(?) also i will need to use the pthreadsGC2 library for the attach/detach_np to work.

But as i can see there are some plugins with license although they are open source!
Maybe not so good to compile them now.definitely i will support this once i have the possibility.
Thnx

**Comment by x42** [comment]
You can remove the `-DRTK_STATIC_INIT` define in `b_whirl/Makefile` for a local build, however plugins must be self-contained, so dynamically linking is not really an option.
