### ISSUE TITLE
Text is not displayed

### ISSUE THREAD

**Issue by Ploppz** [pantherb/setBfree#71]
Arch Linux,
setbfree: 0.8.11, from official Arch Linux repository,
I use it in Ardour 5.12. When I press this button:
![](https://media.discordapp.net/attachments/676404528123478026/713841746387140638/unknown.png)
I see no text:
![](https://media.discordapp.net/attachments/676404528123478026/714919373910835260/21.Tuesday-slop0416.png)

**Comment by Ploppz** [comment]
Just tested with Ardour 6.0.9 - same result.

**Comment by david0** [comment]
I think this is because of #56. Try copying VeraBd.ttf into lv2/b_synth as a workaround.

**Comment by x42** [comment]
Probably an issue with arch build.  -- you could try: https://x42-plugins.com/x42/setBfree
If that works please file an issue request with Arch.

**Comment by Ploppz** [comment]
Yep that one works, thanks.
