### ISSUE TITLE
Toggle whirl speed using cc 64

### ISSUE THREAD

**Issue by david0** [pantherb/setBfree#72]
It would be nice if the external whirl could be toggled using cc 64 directly.
Its possible to automate the parameter, but its kind of hard. It would really be nice if it could be done by the plugin itself.

**Comment by x42** [comment]
Do you mean the standalone Leslie plugin (x42 Whirl - Rotary Speaker) -- not one built into the organ (setBfree DSP Tonewheel Organ)?

**Comment by david0** [comment]
Yes, exacly the standalone one.

**Comment by x42** [comment]
In this case the plugin-host must provide the mapping (MIDI learn to change the control input).

--

That plugin has no MIDI input, and even if it had, a plugin must not modify its own inputs.  Say you send a CC-64 to enable the leslie motor, while at the same time the host uses plugin automation to disable it.  The only way to solve this ambiguity is to put the host in control (or not expose the parameter, like the organ does).

**Comment by david0** [comment]
Oh I see, that old problem. 
Still it could be configurable which source is the master or the plugin could provide a simpler on/off style input. 

I guess to some degree lv2vst is the problem. The enum maps to 0-8, which makes at least Reapers midi learn control it from 0<->8...

**Comment by x42** [comment]
Oh, wrapped via LV2VST?!  You're definitely on your own then, nothing we can do here.
