### ISSUE TITLE
Changing waveform for the tonewheels

### ISSUE THREAD

**Issue by GIBA-BDV** [pantherb/setBfree#89]
Hi,

I'm Giovanni from Brazil, then sorry for my poor English. I'm not a developer too.
I'm new on asking thinks on GitHub. Correct me if I'm wrong, please.

Does have any simple way to change the waveform for the tonewheels?
I would like to add a triangular and a 9 step piramid waveforms to the organ.

The ideia is to imitate a Vox and a Farfisa organ.

Thanks to the support.

**Comment by x42** [comment]
There is currently no way to change the waveform.  The sine-wave (and harmonics) are hard-coded [1].
To add other waveforms you will have to change the source-code.

--

[1] https://github.com/pantherb/setBfree/blob/master/src/tonegen.c#L1234-L1323

**Comment by GIBA-BDV** [comment]
Thanks to the support. God bless you.
